### ISSUE TITLE
win 6.1.4 won't overwrite output files

### ISSUE THREAD

**Issue by speleo** [therion/therion#480] opened 2022-12-28 10:34 UTC
##################### end of pdftex log file #####################
C:\Program Files (x86)\Therion\therion.exe: error -- filesystem error: cannot copy: File exists [C:\Users\...\AppData\Local\Temp\th10908\data.pdf] [cave_name.pdf]
writing xtherion file ... done

I hit this with every survey.  Reverting to 6.1.3 works fine

**Comment by Afforix** [comment] 2022-12-29 10:29
Hi, thanks for your report, it is probably caused by [this MinGW bug](https://sourceforge.net/p/mingw-w64/bugs/852/). We are testing a workaround in pull request #481.

**Comment by mbudaj** [comment] 2022-12-30 17:03
Fixed in 6.1.5.

**Closed by mbudaj** 2022-12-30 17:03 UTC
