### ISSUE TITLE
sketch is displaced in xvi

### ISSUE THREAD

**Issue by jonnyprouty** [therion/therion#332] opened 2021-02-14 17:08 UTC
In the process of making an XVI from several sketches, I came across some strange behavior where the sketches are vertically offset from the survey line plot (screenshot below). I have tested this on the most recent version, therion 5.5.6+82b4a8b (2021-02-06).

Here is what brings this about:
1. I create a new .th2 file, create a single scrap inside it, then import a single sketch as a background image. I then add survey station points (raw data included below). Save, then close.
![Screenshot_2021-02-14_12-02-23](https://user-images.githubusercontent.com/6690721/107883374-a836c200-6ebc-11eb-9268-2a3c4ed6adbc.png)

Bit of sketch that's imported into the .th2 file:
![test](https://user-images.githubusercontent.com/6690721/107883409-d2887f80-6ebc-11eb-81c8-9841f631c8dd.png)

Contents of file single_sketch.th2:
```
##XTHERION## xth_me_area_adjust -128 -631 994 128
##XTHERION## xth_me_area_zoom_to 100
##XTHERION## xth_me_image_insert {0 1 1.0} {0 {}} test.png 0 {}



scrap single_sketch_pl_1 -projection plan -scale [0 0 400 0 0.0 0.0 20 0.0 ft] -sketch [test.png] 0 -2200

point 747.0 -315.0 station -name BA15

point 645.0 -348.0 station -name BA14

point 420.0 -231.0 station -name BA13

point 215.0 -365.0 station -name BA12

point 71.0 -302.0 station -name BA11

endscrap
```

2. Export an xvi composed of only the one sketch. Note that sketch will be rotated on output, since north was down in the sketch.

thconfig used to generate map. I've used a source/endsource pair here for the sake of brevity, but the behavior is the same if the survey is in a dedicated file:
```
source
  survey xvi_test
  centerline
    units length feet
    data normal from to length compass clino
      BA11 BA12  10.6  293.6  14.6
      BA12 BA13  16.8  236.9  12.2
      BA13 BA14  16.2  297.8   1  
      BA14 BA15   8.5  247.1  28.3
    endcenterline

  input single_sketch.th2

  map xvi_test_sketch -proj plan
    single_sketch_pl_1
  endmap xvi_test_sketch
    
  endsurvey xvi_test
endsource

select xvi_test_sketch@xvi_test

export map -proj plan -layout-sketches	on -o test.xvi
```
3. Import xvi into new .th2 file. The sketch is drawn in the wrong place relative to the line plot.
![Screenshot_2021-02-14_11-44-31](https://user-images.githubusercontent.com/6690721/107883011-45dcc200-6eba-11eb-95bf-fad547919803.png)

**Comment by smudrak** [comment] 2021-02-15 19:50
Hmmm, I am afraid Jonny, something like this was never supposed to work. If an XVI image is generated from therion, it has always its own local coordinate system. If you add XVI scatch to .th2, it behaves the same way - as if image is added. It is placed below existing images, regardless of coordinates already assigned to stations in existing scraps. You could have several scraps in the .th2 file with the same stations, therefore it is not taken into consideration.

**Comment by jonnyprouty** [comment] 2021-02-16 05:09
The sketch in the screenshot associated with step #3 above is a sketch that was embedded into the XVI image.  the the morphed sketches won't share the same coordinate system as the XVI that they were generated with? I thought it was possible to have multiple raster images (GIFs) embedded within a single XVI?

**Comment by smudrak** [comment] 2021-02-16 07:15
I am sorry, now I get the message. I have tried, but unfortunately - I am not able to reproduce your issue :/ It looks, there is something in your data that is causing this shift - in both xvi/pdf output. Are you able to create some small sample with this issue and send it to me? Thanks.

**Comment by smudrak** [comment] 2021-02-16 07:41
Looking at your data, maybe I see the issue - but still do not know, how this can happen.
Unfortunately - .th2 background images are not linked to scrap sketches - so if background image is moved, XY in scrap definition of sketch image (scrap ... -sketch <file> X Y) is not changed. In your data, you have:

scrap single_sketch_pl_1 -projection plan -scale [0 0 400 0 0.0 0.0 20 0.0 ft] -sketch [test.png] 0 -2200

- so the image is at -2200 but stations have much higher image coordinates:

point 747.0 -315.0 station -name BA15

at around -315. Might be, it is correct. No idea. But at least deleting and re-inserting scrap background sketches (not .th2 file background images) could help. Now I remember, long time ago it happend to me also... but I have no idea what caused this problem.

**Comment by jonnyprouty** [comment] 2021-02-16 15:36
Hi @smudrak , thanks for having another look. I have attached some of my data that reproduces the result.

[issue_332.zip](https://github.com/therion/therion/files/5989645/issue_332.zip)

The more I think about it, it occurs to me that I may be the source of this. Because I am a lazy person, I wrote a shell script that will generate .th2 files for me given a list of files. It cuts down on the tedium of doing it by hand, but perhaps it has led to more problems. Regardless, in case it helps, here are portions of the pertinent scripts.

Perhaps I screwed up the xth_me_image_insert geometry?

```
# $1 = path to th2 file
# $2 = path fo sketch image file
file_th2_header_print ()
{
# I omitted some stuff here that uses imagemagick to get
# the width and height of the raw image, $2
# sketch_w holds the width of the sketch, in pixels
# sketch_h holds the height of the sketch, in pixels
# I don't remember why I add 128, I wrote this years ago and if I recall
# it was to get the sketch to draw in the correct place.
sketch_w=$(( sketch_w+128 ))
sketch_h=$(( sketch_h+128 ))
cat <<EOF > "$1"
encoding  utf-8
##XTHERION## xth_me_area_adjust -128 -$sketch_h $sketch_w 128
##XTHERION## xth_me_area_zoom_to 100
##XTHERION## xth_me_image_insert {0 1 1.0} {0 {}} {$( basename $2 )} 0 {}

EOF
}
```
Here is where I create an individual scrap. Again, perhaps I messed up the -scale option below. Hmm.
```
# $1 projection type
# $2 path to .th2 file
# $3 name of scrap
# $4 path to sketch image file
file_scrap_print ()
{
cat <<EOF >> "$2"
scrap $3 -projection $1 -scale [0 0 400 0 0.0 0.0 20 0.0 ft] -sketch [$4] 0 -2200 -station-names "" @$(survey_name_get).valhalla

endscrap
EOF
}

```

**Comment by smudrak** [comment] 2021-02-16 20:08
No, xth_me_image insert is OK, but the problem is "-sketch [$4] 0 -2200" - coordinates of each sketch image are 0 -2200 but they should depend on the size of an image (lower left corner is used). If you delete this sketch in xtherion - Scrap->background sketches->Delete and reinsert it - clicking on Insert and then on background image - it is inserted with correct coordinates. For example in scrap ...1_pl_1 you have:

-sketch issue_332_1.gif 0 -2200

but it shoud be:

-sketch issue_332_1.gif 0 -829

If you insert each image by script at 0,0 coordinates, -2200 (constant) in your script should be -image_height. (y-coordinate - image_height in fact). Attached are fixed files. With them, picture position is OK.

[fix.zip](https://github.com/therion/therion/files/5991397/fix.zip)

**Closed by smudrak** 2021-02-16 20:08 UTC

**Comment by smudrak** [comment] 2021-02-16 20:10
If it still does not solve your issue, do not hesitate to reopen it :)

**Comment by jonnyprouty** [comment] 2021-02-16 21:30
> If it still does not solve your issue, do not hesitate to reopen it :)

Thanks so much!
