### ISSUE TITLE
Problem to install on Catalina 10.15.6

### ISSUE THREAD

**Issue by fratnike** [therion/therion#262] opened 2020-08-11 09:24 UTC
Hi,
when I try to install therion on my MAC I receive the following error:
make: *** [thcsdata.h] Segmentation fault: 11

This happen when I try with the direct installation:
- git clone https://github.com/therion/therion.git && cd therion
- brew install lcdf-typetools proj ghostscript vtk libpng zlib libjpeg wxmac freetype ImageMagick tcl-tk
- make config-macosx && make && make install

but also with the Homebrew procedure:
- brew install --HEAD https://raw.githubusercontent.com/ladislavb/homebrew-therion/master/therion.rb

do you have any idea for solving problem?

Thank you in advance

enrico
![Screenshot 2020-08-11 at 11 22 56](https://user-images.githubusercontent.com/6651334/89880901-16749200-dbc5-11ea-97a3-d289adeda773.jpg)
![Screenshot 2020-08-11 at 11 23 21](https://user-images.githubusercontent.com/6651334/89880917-1aa0af80-dbc5-11ea-9b98-114d2d953ddc.jpg)

**Comment by mbudaj** [comment] 2020-08-12 12:01
Hi,

we build therion (actually just therion, loch and tests binaries) on a slightly older 10.15.5 without any problems (see e.g. https://travis-ci.org/github/therion/therion/jobs/717056151). 

Your two logs seem to fail in different stages. More detailed logs would be helpful.

It would be also helpful if you check whether the method we use on Travis works on your system (see the "osx" lines in https://github.com/therion/therion/blob/master/.travis.yml).

**Comment by fratnike** [comment] 2020-08-12 12:40
Hi,

I have tried the "OSX" sequence of https://github.com/therion/therion/blob/master/.travis.yml and the error persist:

brew update
Updated 2 taps (homebrew/core and homebrew/cask).
...
...

brew tap homebrew/core

brew unlink python@3.8 (I do not have python@2)
Unlinking /usr/local/Cellar/python@3.8/3.8.5... 25 symlinks removed

brew install wxmac vtk
Warning: wxmac 3.0.5.1_1 is already installed and up-to-date
To reinstall 3.0.5.1_1, run `brew reinstall wxmac`
Warning: vtk 8.2.0_10 is already installed and up-to-date
To reinstall 8.2.0_10, run `brew reinstall vtk`

make config-macosx
perl makeconfig.pl PLATFORM MACOSX
cd loch; perl makeconfig.pl PLATFORM MACOSX

make ./therion
python3 set_version.py
echo "[PROJ]" > innosetup.ini && echo "version=7" >> innosetup.ini
tclsh thcsdata.tcl 
make: *** [thcsdata.h] Segmentation fault: 11

Please tell me which logs you want

thank you 

enrico

**Comment by IdlePhysicist** [comment] 2020-08-12 14:35
@fratnike running `brew install --verbose --HEAD https://raw.githubuser...` will produce much more detailed logs.

**Comment by fratnike** [comment] 2020-08-12 14:48
Thank you @IdlePhysicist for your help!

Attached the extended log.

enrico
[therion_install_log.txt](https://github.com/therion/therion/files/5063500/therion_install_log.txt)

**Comment by IdlePhysicist** [comment] 2020-08-12 15:24
I took a quick look at you logfile, I have seen that error before several times, it only appears when building with Homebrew. 

The issue is with the Homebrew formula that you're using. The formula needs to tell Homebrew to not make components in parallel, effectively this is being caused by `thchencdata.cxx` not existing (it is a generated file) when it is needed by another make target. To remedy this you can tap and use my formula ([IdlePhysicist/homebrew-caving](https://github.com/IdlePhysicist/homebrew-caving)), which includes the necessary `ENV.deparallelize` command in the formula. If there is an issue with my formula please feel free to open an issue in my repo.

As for the Segmentation fault when you build manually, I am unsure what is going on here. The Therion devs might be better able to help than me.

**Comment by mbudaj** [comment] 2020-08-13 12:47
It seems that the following fails; can you confirm it by running it manually instead of make?
`tclsh thcsdata.tcl`
If it fails with a segfault, run also `pkg-config proj --variable=prefix`, which is the only external command executed from that tcl script.

**Comment by fratnike** [comment] 2020-08-13 13:34
enricof@icts-enrico therion % tclsh thcsdata.tcl
zsh: segmentation fault  tclsh thcsdata.tcl
enricof@icts-enrico therion % pkg-config proj --variable=prefix
/usr/local/Cellar/proj/7.1.0
enricof@icts-enrico therion %

**Comment by mbudaj** [comment] 2020-08-13 14:16
It's not quite expected to get segfault from the interpreter. I suspect
there could be a problem in the Tcl installation itself. You could try if
tclsh is able to process other tcl scripts and if yes, try some of the
techniques mentioned here
https://wiki.tcl-lang.org/page/What+debugging+tools+are+available+to+a+Tcl+programmer
on the problematic file.
M.

**Comment by mbudaj** [comment] 2020-08-19 06:09
Check out the latest commit in the master branch. It uses a different
approach to labels handling for newer Proj versions.

**Comment by fratnike** [comment] 2020-08-19 06:55
Thank you Martin,

   now I am able to compile the source with OSX 10.15.6 !!!

I have received some warning... you can find attached the "make install" output.

Thank you for all

enrico
[therion_install_log5.txt](https://github.com/therion/therion/files/5094518/therion_install_log5.txt)

**Comment by mbudaj** [comment] 2020-08-20 17:30
Some of the warnings (illegal character encoding in string literal) have already been fixed in the devel branch. The others still need to be fixed, but they are mostly harmless.

**Closed by mbudaj** 2020-08-20 17:30 UTC
